//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderProduct
    {
        public int CustomerOrderProductID { get; set; }
        public int CustomerOrderID { get; set; }
        public int ProductID { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Product Product { get; set; }

        public string ProductnameAndAmount
        {
            get
            {
                return Product.Name + " " + CustomerOrder.Amount;
            }
        }
    }
}
