//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Logins = new HashSet<Login>();
            this.Orders = new HashSet<Order>();
            this.Payslips = new HashSet<Payslip>();
        }
    
        public int EmployeeID { get; set; }
        public int AccessID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime EmploymentDate { get; set; }
        public decimal StartingSalary { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }

        public virtual Access Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payslip> Payslips { get; set; }
        public string FullName
        {
            get
            {
                return Lastname + " " + Firstname;
            }
        }
    }
}
