//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leverancier
    {
        public string Leveranciernaam { get; set; }
        public int LeverancierID { get; set; }
        public int Telefoonnummer { get; set; }
        public string Email { get; set; }
        public string Straatnaam { get; set; }
        public Nullable<int> Huisnummer { get; set; }
        public string Bus { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Gemeente { get; set; }
    }
}
