//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        public int PayslipID { get; set; }
        public int EmployeeID { get; set; }
        public int MonthID { get; set; }
        public decimal Seniority { get; set; }
        public decimal SocialSecurity { get; set; }
        public decimal WithholdingTax { get; set; }
        public decimal Gross { get; set; }
        public decimal Net { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Month Month { get; set; }
    }
}
