//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderProduct
    {
        public int SupplierOrderProductID { get; set; }
        public int SupplierOrderID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
    }
}
