//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazijnProject.Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public decimal Margin { get; set; }
        public int Tax { get; set; }
        public int CategoryID { get; set; }
        public int SupplierID { get; set; }
        public bool InStock { get; set; }
        public int AmountInStock { get; set; }
        public Nullable<int> AmountInOrder { get; set; }
        public Nullable<int> AmountInBackorder { get; set; }
        public Nullable<int> AmountAvailable { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
